# Note: It seems that cache doesn't work when "sudo: required". :(
sudo: required
dist: trusty
language: node_js
env:
  global:
    - PROJ_NAME=react-pdf

install:
  # Download and verify alpine-chroot-install script.
  - wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.2.0/alpine-chroot-install
      && echo '7c6f0550f02d853d7275cfa82529e62a3a09d629  alpine-chroot-install' | sha1sum -c
  # Install Alpine Linux into /alpine and prepare there a chroot environment;
  # use branch edge (i.e. unstable), add testing repository and install
  # packages for Emscripten.
  - sudo sh alpine-chroot-install -b edge
      -r 'https://nl.alpinelinux.org/alpine/edge/testing'
      -p emscripten -p emscripten-libs-asmjs -p closure-compiler

node_js:
 - '7'
 - '6'

os:
 - osx

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
  - node_modules

install: yarn

script: yarn test
